### PR TITLE
update widevine and omx, this fixes youtube playback for zl1

### PR DESCRIPTION
**Pull request by mosimchah**

### CODE REVIEW

**Comment by mosimchah** [comment]
closing for now, needs more work

**Comment by jrior001** [comment]
Source of these blobs?

**Comment by mosimchah** [comment]
here https://github.com/darkobas/proprietary_vendor_leeco

**Comment by mosimchah** [comment]
I need to fix it a bit though

**Comment by mosimchah** [comment]
It's unnecessary now https://github.com/TheMuppets/proprietary_vendor_leeco/commit/030917f002f6cc593bb3b84b6742841da633852f

**Pull request closed without merging**
