### PR TITLE
added x500 blobs

### PR DESCRIPTION
**Pull request by SscSPs**
added files for Leeco Le 1s

### CODE REVIEW

**Comment by SscSPs** [comment]
Can anyone tell me why is this not being merged?

**Comment by Tortel** [comment]
Theres no Lineage/CM tree for it, so it doesnt belong here

**Comment by Tortel** [comment]
If you have a working device tree, you can submit it for inclusion Lineage by emailing devrel@lineageos.org

If that doesnt work, I can help get the process started

**Comment by SscSPs** [comment]
okay

**Pull request closed without merging**
